export const SET_USER_ID = "SET_USER_ID";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_THEME = "SET_THEME";
export const RESET_LIST = "RESET_LIST";
export const ADD_ORDER_TO_LIST = 'ADD_ORDER_TO_LIST';
export const REMOVE_ORDER_FROM_LIST = 'REMOVE_ORDER_FROM_LIST';
export const INCREASE_ORDER_COUNT = 'INCREASE_ORDER_COUNT';
export const DECREASE_ORDER_COUNT = 'DECREASE_ORDER_COUNT';